### ISSUE TITLE
MVSX Controls Are Jacked

### ISSUE THREAD

**Issue by molnara** [acmeplus/RetroArch-ASP#2]
## Description

The default retroarch controls for MVSX are setup poorly that will frustrate many.  The first 1P white button(the one beside the red one) is mapped to both back and quit buttons.

### Expected behavior

I should be able to easily change the default controls.

### Actual behavior

The 1P white(right from red button) is mapped to both back and quit buttons.  This is obviously an issue as if you hit the back button twice within 5 seconds or so, retroarch quits.  The user is then greeted with a black screen.  On mine at least, I think the hack menu is supposed to load after retroarch quits.

### Default control id's
I've mapped what the joystick id's are if it helps:

Buttons at the top:
1p Start=4
Options Back=1
Select=18
2P Start=16

**1 Player**
_Buttons:_
Red=24
Yellow=3
Green=0
Blue=7
White (beside red button)=11
White=6
_Joystick:_
Up=12
Right=10
Down=9
Left=8

**2 Player**
_Buttons:_
Red=25
Yellow=26
Green=29
Blue=Mouse3
White (beside red button)=23
White=22
_Joystick:_
Up=20
Right=17
Down=21
Left=19

**Comment by acmeplus** [comment]
Thanks for the update. I don't have a MVSX, so I know default mapping is not correct. There will be an update at some point with the right retroarch.cfg that includes P1 & P2. The file attached to this ticket was created by another user, let me know if it works well for you and I'll include it in another build.
[retroarch-mvsx.cfg.zip](https://github.com/acmeplus/RetroArch-ASP/files/6080482/retroarch-mvsx.cfg.zip)
