### ISSUE TITLE
Any filter?

### ISSUE THREAD

**Issue by MVSX** [acmeplus/RetroArch-ASP#3]
I would like to load some shaders to enhance the final video effect which is really very pixelated. Unfortunately even putting Shaders in the folder doesn't see me then on MVSX. Can anyone help me? Is it possible that nothing can be done to improve the viewing experience with these games?

**Comment by yayacannes** [comment]
I have the same request and the same issue... Just missing that great feature !

**Comment by acmeplus** [comment]
For the new release, the filters can be located in /usr/share/video_filters, just add that path in retroarch config

https://github.com/acmeplus/RetroArch-ASP/releases/tag/v1.16_mvsx_20240122
